package tests;

import businesslogic.entities.Aircraft;
import datalayer.dao.AircraftDAO;
import datalayer.impl.AircraftDAOImpl;

import java.sql.SQLException;
import java.util.List;

public class TestAircraftDAO {

    public static void main(String[] args) {
        AircraftDAO aircraftDAO = new AircraftDAOImpl();

        try {
            System.out.println("==== TEST: SAVE ====");
            Aircraft aircraft = new Aircraft(
                    0,                     // ID will be generated by DB
                    "737-800",
                    "Boeing",
                    180,
                    "3-3",
                    "ACTIVE"
            );

            aircraftDAO.save(aircraft);
            System.out.println("Saved aircraft with ID: " + aircraft.getAircraftId());

            System.out.println("\n==== TEST: FIND BY ID ====");
            Aircraft found = aircraftDAO.findById(aircraft.getAircraftId());
            System.out.println("Found aircraft: " + found);

            System.out.println("\n==== TEST: UPDATE ====");
            found.setModel("737-900");
            found.setTotalSeats(190);
            found.setStatus("MAINTENANCE");

            boolean updated = aircraftDAO.update(found);
            System.out.println("Update result: " + updated);

            Aircraft updatedFromDb = aircraftDAO.findById(found.getAircraftId());
            System.out.println("Updated aircraft from DB: " + updatedFromDb);

            System.out.println("\n==== TEST: FIND ALL ====");
            List<Aircraft> all = aircraftDAO.findAll();
            System.out.println("Total aircraft in DB: " + all.size());
            for (Aircraft a : all) {
                System.out.println(a);
            }

            System.out.println("\n==== TEST: DELETE ====");
            boolean deleted = aircraftDAO.delete(found.getAircraftId());
            System.out.println("Delete result: " + deleted);

            Aircraft afterDelete = aircraftDAO.findById(found.getAircraftId());
            System.out.println("Find after delete (should be null): " + afterDelete);

            System.out.println("\n==== TESTS COMPLETED ====");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
