package tests;

import businesslogic.entities.Payment;
import businesslogic.entities.enums.PaymentMethod;
import businesslogic.entities.enums.PaymentStatus;
import datalayer.dao.PaymentDAO;
import datalayer.impl.PaymentDAOImpl;

import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.List;

public class TestPaymentDAO {

    public static void main(String[] args) {
        PaymentDAO paymentDAO = new PaymentDAOImpl();

        try {
            System.out.println("==== TEST: SAVE ====");
            Payment payment = new Payment(
                    0, // ID will be generated by DB
                    299.99,
                    LocalDateTime.now(),
                    PaymentMethod.CREDIT_CARD,
                    "TXN-ABC12345",
                    PaymentStatus.COMPLETED
            );

            Payment saved = paymentDAO.save(payment);
            System.out.println("Saved payment with ID: " + saved.getPaymentId());
            System.out.println("Payment: " + saved);

            System.out.println("\n==== TEST: FIND BY ID ====");
            Payment found = paymentDAO.findById(saved.getPaymentId());
            System.out.println("Found payment: " + found);

            System.out.println("\n==== TEST: FIND BY TRANSACTION ID ====");
            Payment byTransaction = paymentDAO.findByTransactionId("TXN-ABC12345");
            System.out.println("Found by transaction ID: " + byTransaction);

            System.out.println("\n==== TEST: UPDATE ====");
            found.setStatus(PaymentStatus.REFUNDED);
            boolean updated = paymentDAO.update(found);
            System.out.println("Update result: " + updated);

            Payment updatedFromDb = paymentDAO.findById(found.getPaymentId());
            System.out.println("Updated payment from DB: " + updatedFromDb);

            System.out.println("\n==== TEST: FIND ALL ====");
            List<Payment> all = paymentDAO.findAll();
            System.out.println("Total payments in DB: " + all.size());
            for (Payment p : all) {
                System.out.println(p);
            }

            System.out.println("\n==== TEST: DELETE ====");
            boolean deleted = paymentDAO.delete(found.getPaymentId());
            System.out.println("Delete result: " + deleted);

            Payment afterDelete = paymentDAO.findById(found.getPaymentId());
            System.out.println("Find after delete (should be null): " + afterDelete);

            System.out.println("\n==== TESTS COMPLETED ====");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

